services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
  
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_PROD_URL:-postgresql://genealogy_user:genealogy_password@postgres-prod:5432/genealogy_db}
    depends_on:
      postgres-prod:
        condition: service_healthy

  postgres-prod:
    image: postgres:16.10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-genealogy_db}
      - POSTGRES_USER=${POSTGRES_USER:-genealogy_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-genealogy_password}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-genealogy_user} -d ${POSTGRES_DB:-genealogy_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_prod_data:
