services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
  
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
