services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
  
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://genealogy_user:genealogy_password@postgres-prod:5432/genealogy_db}
    depends_on:
      - postgres-prod

  postgres-prod:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-genealogy_db}
      - POSTGRES_USER=${POSTGRES_USER:-genealogy_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-genealogy_password}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
