name: Main pipeline used for testing, linting and mirroring the repository

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_REPO_URL: "git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-14.git"

jobs:
  checkout-and-artifact:
    name: Checkout and upload code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .

  build-dev:
    name: Build the development environment
    runs-on: ubuntu-latest
    needs: checkout-and-artifact
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Build the development environment
        run: |
          make up-dev
          docker save server-dev -o server-dev.tar || true
          docker save client-dev -o client-dev.tar || true

      - name: Upload built images
        uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: |
            awkward-legacy-server-dev.tar
            awkward-legacy-client-dev.tar

  run-server-tests:
    name: Run the development server tests
    runs-on: ubuntu-latest
    needs: run-server-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .
      
      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: .

      - name: Load Docker images
        run: |
          docker load -i awkward-legacy-server-dev.tar || true
          docker load -i awkward-legacy-client-dev.tar || true

      - name: Run the development server tests
        run: |
          make test-server
    
  run-client-tests:
    name: Run the development client tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .
      
      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: .

      - name: Load Docker images
        run: |
          docker load -i awkward-legacy-server-dev.tar || true
          docker load -i awkward-legacy-client-dev.tar || true

      - name: Run the development client tests
        run: |
          make test-client

  run-client-e2e-tests:
    name: Run the development client e2e tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: .

      - name: Load Docker images
        run: |
          docker load -i awkward-legacy-server-dev.tar || true
          docker load -i awkward-legacy-client-dev.tar || true

      - name: Run the development client e2e tests
        run: |
          make test-client-e2e

  run-server-lint:
    name: Run the development server lint
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: .

      - name: Load Docker images
        run: |
          docker load -i awkward-legacy-server-dev.tar || true
          docker load -i awkward-legacy-client-dev.tar || true

      - name: Run the development server lint
        run: |
          make lint-server

  run-client-lint:
    name: Run the development client lint
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .
      
      - name: Download built images
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: .

      - name: Load Docker images
        run: |
          docker load -i awkward-legacy-server-dev.tar || true
          docker load -i awkward-legacy-client-dev.tar || true

      - name: Run the development client lint
        run: |
          make lint-client

  mirror:
    name: Mirror the repository files to another repository
    runs-on: ubuntu-latest
    needs: [run-server-lint, run-client-lint]
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
