name: Main pipeline used for testing, linting and mirroring the repository

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_REPO_URL: "git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-14.git"

jobs:
  checkout-and-artifact:
    name: Checkout and upload code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Upload code artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  build-dev-server:
    name: Build the development server
    runs-on: ubuntu-latest
    needs: checkout-and-artifact
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Build the development server
        run: |
          make build-dev-server

  build-dev-client:
    name: Build the development client
    runs-on: ubuntu-latest
    needs: checkout-and-artifact
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Build the development client
        run: |
          make build-dev-client

  run-server-tests:
    name: Run the development server tests
    runs-on: ubuntu-latest
    needs: run-server-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Run the development server tests
        run: |
          make test-server
    
  run-client-tests:
    name: Run the development client tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Run the development client tests
        run: |
          make test-client

  run-client-e2e-tests:
    name: Run the development client e2e tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Run the development client e2e tests
        run: |
          make test-client-e2e

  run-server-lint:
    name: Run the development server lint
    runs-on: ubuntu-latest
    needs: build-dev-server
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Run the development server lint
        run: |
          make lint-server

  run-client-lint:
    name: Run the development client lint
    runs-on: ubuntu-latest
    needs: build-dev-client
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Run the development client lint
        run: |
          make lint-client

  mirror:
    name: Mirror the repository files to another repository
    runs-on: ubuntu-latest
    needs: [run-server-lint, run-client-lint]
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v3
        with:
          name: source-code
          path: .

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
