name: Main pipeline used for testing, linting and mirroring the repository

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_REPO_URL: "git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-14.git"

jobs:
  build-prod:
    name: Build the production environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build production environment
        run: |
          make up-prod
          timeout 60s bash -c 'until docker compose -f docker-compose.prod.yml ps | grep -q "healthy"; do sleep 2; done'

      - name: Test production endpoints
        run: |
          docker compose -f docker-compose.prod.yml exec -T client-prod wget -q -O /dev/null http://server-prod:8000/ || exit 1
          docker compose -f docker-compose.prod.yml exec -T server-prod wget -q -O /dev/null http://client-prod:80/ || exit 1

      - name: Cleanup production environment
        run: make down-prod

  build-dev:
    name: Build the development environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build production environment
        run: |
          make up-dev
          timeout 60s bash -c 'until docker compose -f docker-compose.dev.yml ps | grep -q "healthy"; do sleep 2; done'
      
      - name: Test development endpoints
        run: |
          docker compose -f docker-compose.dev.yml exec -T client-dev wget -q -O /dev/null http://server-dev:8000/ || exit 1
          docker compose -f docker-compose.dev.yml exec -T server-dev wget -q -O /dev/null http://client-dev:5173/ || exit 1     
      - name: Down the development environment
        run: |
          make down-dev

      - name: Cleanup development environment
        run: make down-dev

  run-server-tests:
    name: Run the development server tests
    runs-on: ubuntu-latest
    needs: run-server-lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the development server tests
        run: |
          make test-server
    
  run-client-tests:
    name: Run the development client tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the development client tests
        run: |
          make test-client

  run-client-e2e-tests:
    name: Run the development client e2e tests
    runs-on: ubuntu-latest
    needs: run-client-lint
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the development client e2e tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          make test-client-e2e-parallel shard=${{ matrix.shard }} total-shards=${{ matrix.total-shards }} ci-build-id=${{ github.run_id }}-${{ matrix.shard }}

  run-server-lint:
    name: Run the development server lint
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the development server lint
        run: |
          make lint-server

  run-client-lint:
    name: Run the development client lint
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the development client lint
        run: |
          make lint-client

  mirror:
    name: Mirror the repository files to another repository
    runs-on: ubuntu-latest
    needs: [run-server-tests, run-client-tests, run-client-e2e-tests, build-prod]
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
