name: SonarQube

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        working-directory: back
        run: |
          pytest --cov=src --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=back/src
            -Dsonar.tests=back/tests
            -Dsonar.python.coverage.reportPaths=back/coverage.xml
