name: SonarQube

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.10-alpine
        env:
          POSTGRES_USER: sonarqube
          POSTGRES_PASSWORD: sonarqube
          POSTGRES_DB: sonarqube_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  # or your version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements-dev.txt
          pip install pytest pytest-cov

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Run backend tests with coverage
        working-directory: server
        env:
          DATABASE_URL: postgresql://sonarqube:sonarqube@localhost:5432/sonarqube_db
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest --cov=src --cov-report=xml:coverage.xml

      - name: Run frontend tests with coverage
        working-directory: client
        run: npm run test:unit:coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=server/src,client/src
            -Dsonar.tests=server/tests,client/src/__tests__
            -Dsonar.python.coverage.reportPaths=server/coverage.xml
            -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/__tests__/**,**/*.spec.ts,**/*.test.ts
            -Dsonar.test.inclusions=**/__tests__/**/*,**/*.spec.ts,**/*.test.ts
