name: SonarQube

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.10-alpine
        env:
          POSTGRES_USER: sonarqube
          POSTGRES_PASSWORD: sonarqube
          POSTGRES_DB: sonarqube_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements-dev.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        working-directory: server
        env:
          DATABASE_URL: postgresql://sonarqube:sonarqube@postgres:5432/sonarqube_db
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest --cov=src --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=server/src
            -Dsonar.tests=server/tests
            -Dsonar.python.coverage.reportPaths=server/coverage.xml
